---
title: "Build Operating Models for SA Species"
author: "Nikolai"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE, echo=FALSE}
rm(list=ls())
knitr::opts_chunk$set(comment=NA,echo=FALSE,message=FALSE,warning=FALSE,fig.height=8,fig.width=6)

library(car)
library(faux) # Simulation for Factorial Designs
# devtools::install_github("james-thorson/FishLife")
library(FishLife)
library(Hmisc)
library(MultiRNG) # Multivariate Pseudo-Random Number Generation
library(measurements) # Unit conversion functions like conv_unit()
library(openMSE)
library(rfishbase)
library(stringr)
 
library(bamExtras) # Nikolai's package

```

```{r user}
length_sc <- 0.1 # Scalar (multiplier) to convert length units. MSEtool examples seem to use cm whereas BAM uses mm.
plot_OM <- TRUE # Switch for plotting OM. It takes a while to plot them all

# OM
nsim <- 250 # The number of simulations (48 is the minimum number you can run in parallel)
proyears <- 50 # The number of projected years
interval <- 1  # The assessment interval - how often would you like to update the management system? (should be set to 1 when using the make_interim_MP function using)
set_Fage0_to_zero <- TRUE # Should we assume F-at-age zero is zero for stocks where age zero was not modeled?
```

```{r user bam species}
bam_common_name_sub <- c(
  "BlackSeaBass",
  #"BluelineTilefish",
  #"Cobia",
  #"GagGrouper",
  #"GrayTriggerfish",
  #"GreaterAmberjack",
  #"MenhadenAtl",
  #"RedGrouper",
  "RedPorgy",
  #"RedSnapper",
  #"SnowyGrouper",
  #"SpanishMackerel",
  #"Tilefish",
  "VermilionSnapper"
  )

bam_rdat_sub <- paste("rdat",bam_common_name_sub,sep="_")

```

```{r build OM VPA2OM, eval=TRUE}
list_Nage_F0_pr_sc <- list() # List for storing values of Nage_F0_pr_sc
vec_to_mat <- function(vec){
  matrix(vec,nrow=dim(naa)[2],ncol=dim(naa)[3],byrow=FALSE,
                    dimnames=dimnames(naa)[2:3])
}

mat_to_array <- function(mat,nsim){
  mat_data <- rep(as.numeric(mat),each=nsim)
  array(mat_data, dim=c(nsim,nrow(mat),ncol(mat)),
               dimnames=list("sim"=1:nsim, "ages"=rownames(mat), "year"=colnames(mat)))
}

for(rdat_name_i in bam_rdat_sub){
  rdat_i <- standardize_rdat(get(rdat_name_i))
  Name_i <- gsub("rdat_","",rdat_name_i)
  herm_i <- bamStockMisc[Name_i, "herm"]
  OM_name_i <- gsub("rdat","OM",rdat_name_i)
  a.series_i <- rdat_i$a.series
  t.series_i <- rdat_i$t.series
  
  ageinit_i <- a.series_i$age
  ageinitmin_i <- min(ageinit_i)
  parms_i <- rdat_i$parms
  parm.cons_i <- rdat_i$parm.cons
  
  years_i <- paste(parms_i$styr:parms_i$endyr)
  
  Linf_i <- parm.cons_i$Linf[8]*length_sc
  K_i <- parm.cons_i$K[8]
  t0_i <- parm.cons_i$t0[8]
  steep_i <- parm.cons_i$steep[8]
  R0_i <- exp(parm.cons_i$log_R0[8])
  
  # Compute the number of years at the end of the assessment where rec devs weren't estimated
  nyrNoRecDevEnd <- if (any(t.series_i$logR.dev!=0)) {
    length(t.series_i$logR.dev)-max(which(t.series_i$logR.dev!=0))}else{
      1
    }
  
if(min(ageinit_i)>0){
  warning(paste(Name_i,": Minimum age > 0. Age-based data extrapolated to age-0"))
  a.series_i <- data_polate(a.series_i,xout=0:max(a.series_i$age))
  a.series_i <- data_lim(a.series_i,xlim=c(0,Inf))
  a.series_i <- data_lim(a.series_i,xname=c("prop.female","prop.male","mat.female","mat.male"),xlim=c(0,1))
  a.series_i <- as.data.frame(a.series_i)
  rownames(a.series_i) <- a.series_i$age
}
  
  age_i <- a.series_i$age
  
  # NOTE: this will have no effect in ageinitmin_i=0 
  Nage_F0_pr <- expDecay(age=age_i,Z=a.series_i$M,N0=1)                  # Unfished N-at-age per recruit
  Nage_F0_pr_sc <- (Nage_F0_pr/Nage_F0_pr[[paste(ageinitmin_i)]])[["0"]] # Scaling factor for computing unfished numbers at age-0
  R0_i <- R0_i*Nage_F0_pr_sc                                             # Scaled value of R0
  
  naa_mat <- cbind("age"=ageinit_i,t(rdat_i$N.age[years_i,]))
  naa_mat2 <- data_polate(naa_mat,xout = age_i)
  rownames(naa_mat2) <- age_i
  naa_mat2["0",-1] <- naa_mat2[paste(ageinitmin_i),-1]*Nage_F0_pr_sc # Compute numbers at age-0
  naa_mat2[naa_mat2<0] <- 1 # Don't let value be less than 1
  naa <- mat_to_array(naa_mat2[,-1],nsim=nsim)
  
  faa_mat <- cbind("age"=ageinit_i,t(rdat_i$F.age[years_i,]))
  faa_mat2 <- data_polate(faa_mat,xout = age_i)
  rownames(faa_mat2) <- age_i
  faa_mat2[faa_mat2<0] <- 0 # Don't let F be negative
  if(set_Fage0_to_zero){
    faa_mat2["0",-1] <- 0 # Set F at age-0 to zero
  }
  
  faa <- mat_to_array(faa_mat2[,-1],nsim=nsim)
  
  mat_waa_klb <- matrix(a.series_i$wgt.klb,
                        nrow=dim(naa)[2],ncol=dim(naa)[3],byrow=FALSE,
                        dimnames=dimnames(naa)[2:3])
  waa <- mat_to_array(mat_waa_klb,nsim=nsim)
  
  mat_pmat <- matrix(pmatage(a.series_i,herm=herm_i)$pmat,
                        nrow=dim(naa)[2],ncol=dim(naa)[3],byrow=FALSE,
                        dimnames=dimnames(naa)[2:3])
  Mataa <- mat_to_array(mat_pmat,nsim=nsim)
  
  mat_M <- matrix(a.series_i$M,
                        nrow=dim(naa)[2],ncol=dim(naa)[3],byrow=FALSE,
                        dimnames=dimnames(naa)[2:3])
  Maa <- mat_to_array(mat_M,nsim=nsim)
  
  mat_laa <- matrix(a.series_i$length*length_sc,
                        nrow=dim(naa)[2],ncol=dim(naa)[3],byrow=FALSE,
                        dimnames=dimnames(naa)[2:3])
  laa <- mat_to_array(mat_laa,nsim=nsim)
  
  CurrentYr_i = parms_i$endyr
  
 OM_i <- VPA2OM(Name=Name_i,
                proyears = proyears,
                interval = interval,
                CurrentYr = CurrentYr_i,
                h=steep_i, R0=R0_i,
                Obs = MSEtool::Imprecise_Unbiased,
                Imp = MSEtool::Perfect_Imp,
                naa=naa, faa=faa, waa=waa, Mataa=Mataa, Maa=Maa, laa=laa,
                nyr_par_mu = 3,
                LowerTri = nyrNoRecDevEnd,
                recind = 0,
                plusgroup = TRUE,
                altinit = 0,
                fixq1 = TRUE,)
 
 
 
 OM_i@cpars$K <- rep(K_i,nsim)
 OM_i@cpars$Linf <- rep(Linf_i,nsim)
 OM_i@cpars$t0 <- rep(t0_i,nsim)
 
 
 list_Nage_F0_pr_sc[[Name_i]] <- Nage_F0_pr_sc
 
 # Save rdat modifications
 rdatmods_name_i <- gsub("rdat","rdatmods",rdat_name_i)
 assign(rdatmods_name_i,
        list(
          "Name"=Name_i,
          "CurrentYr" = CurrentYr_i,
          "steep"=steep_i,
          "R0"=R0_i,
          "a.series"=a.series_i,
          "Nage_F0_pr_sc" = Nage_F0_pr_sc,
          "N.age" = t(naa_mat2[,-1]),
          "F.age" = t(faa_mat2[,-1]),
          "B.age" = t(naa_mat2[,-1])*t(mat_waa_klb)
          
          )
        )
 
 
 assign(OM_name_i,OM_i)
}  
```

```{r generate Hist and save OM}
OM_name_bam <- gsub("rdat","OM",bam_rdat_sub) # OM names from bam models

if(plot_OM){
  
for(OM_name_i in OM_name_bam){
  OM_i <- get(OM_name_i)
  
  cat(paste0("\n\nWorking on ",OM_name_i,"\n"))
  Hist_i <- MSEtool::Simulate(OM_i) # Generate historical data

  if(OM_name_i%in%OM_name_bam){
  Hist_name_i <- gsub("OM","Hist",OM_name_i)
  assign(Hist_name_i,Hist_i)
  saveRDS(Hist_i, file = file.path("Hist","SEFSC",paste0(Hist_name_i,".rds")))
  saveRDS(OM_i,file=file.path("OM","SEFSC",paste0(OM_name_i,".rds")),compress=FALSE)
  }
  
}
}
```

```{r plot Hist with bam  results, eval=TRUE}
pdf("HistBam.pdf")
CIpct = 95

for(i in bam_common_name_sub){
rdat_name_i <- paste0("rdat_",i)
rdatmods_name_i <- gsub("rdat","rdatmods",rdat_name_i)
  
OM_i <- get(paste0("OM_",i))
# Data_i <- get(paste0("Data_",i))
Hist_i <- get(paste0("Hist_",i))
rdat_i <- get(rdat_name_i)
rdatmods_i <- get(rdatmods_name_i)

parms_i <- rdat_i$parms
years_i <- paste(parms_i$styr:parms_i$endyr)
t.series_i <- rdat_i$t.series[years_i,]

Nage_F0_pr_sc_i <- list_Nage_F0_pr_sc[[i]]

par(mfrow=c(3,2),mgp=c(0.9,0.1,0),tck=-0.01,mar=c(2,2.5,1,1),oma=c(0,0,1.5,1))



# Landings
Lmatrix <- Hist_i@TSdata$Landings[,,1]+Hist_i@TSdata$Landings[,,2]
Lbam <- t.series_i$total.L.klb
Dbam <- t.series_i$total.D.klb
if(!is.null(Dbam)){
  Lbam <- Lbam+Dbam
}
Lylim <- range(c(0,as.numeric(Lmatrix),Lbam))
plot_boot_vec(Lmatrix,CIpct=CIpct,xlab="year",ylab="Landings + Discards (1000 lb)",ylim=Lylim)
points(Lbam,type="o",#axes=FALSE,xlab="",ylab="",
     col="blue")


# Indices
plot_boot_vec(Hist_i@Data@Ind,CIpct=CIpct,xlab="year",ylab="Ind")
 
# Recruitment
Rmatrix <- Hist_i@AtAge$Number[,1,,1]+Hist_i@AtAge$Number[,1,,2]
plot_boot_vec(Rmatrix,CIpct=CIpct,xlab="year",ylab="recruits")
points(t.series_i$recruits*Nage_F0_pr_sc_i,type="o", col="blue")


# N
Nmatrix <- Hist_i@TSdata$Number[,,1]+Hist_i@TSdata$Number[,,2]
bam.N <- rowSums(rdatmods_i$N.age)
plot_boot_vec(Nmatrix,CIpct=CIpct,xlab="year",ylab="N")
points(bam.N,type="o",col="blue")

# F
Fmatrix <- Hist_i@TSdata$Find
plot_boot_vec(Fmatrix,CIpct=CIpct,xlab="year",ylab="F")
# par(new=TRUE)
 points(t.series_i$year,t.series_i$F.full,type="o",
     col="blue")


# B
Bmatrix <- Hist_i@TSdata$Biomass[,,1]+Hist_i@TSdata$Biomass[,,2]
bam.Bklb <- rowSums(rdatmods_i$B.age)
plot_boot_vec(Bmatrix,CIpct=CIpct,xlab="year",ylab="Biomass (1000 lb)")
par(new=TRUE)
points(bam.Bklb,type="o", #axes=FALSE,xlab="",ylab="",
     col="blue")

mtext(i,side=3,line=0,outer=TRUE)


}
dev.off()
```
