---
title: "OM problems"
author: "Nikolai"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE, echo=FALSE}
rm(list=ls())
knitr::opts_chunk$set(comment=NA,echo=FALSE,message=FALSE,warning=FALSE,fig.height=8,fig.width=6)

library(car)
library(DLMtool)
library(MSEtool)
library(stringr)
 
library(bamExtras) # Nikolai's package
```


# Sorting out issues with OMs as setup in the original Huynh code

```{r}
scenario <- c("base", "hs", "dep", "hd", "lf", "epiM")
OM_name <- c("capelin", "POP", "vs")
OM_names <- paste0("OM_",rep(OM_name,each=length(scenario)), "_", scenario)

env.H1 <- new.env()
env.H2 <- new.env()
load("OM_modified/OMs_correct.RData",envir=env.H1)
load("OM_modified/OMs_wrong.RData",envir=env.H2)

pars_mod_init <- data.frame("OM"=OM_names,"beta"=rep(NA,length(OM_names)),"cparsD"=rep(NA,length(OM_names)))
rownames(pars_mod_init) <- OM_names
pars_mod1 <- pars_mod2 <- pars_mod_init

for(OMname_i in OM_names){
  OM_i <- get(OMname_i,envir=env.H1)
  pars_mod1[OMname_i,c("beta","cparsD")] <- c(paste(round(OM_i@beta,2),collapse=", "),paste(round(head(OM_i@cpars$D,3),3),collapse=", "))
}

for(OMname_i in OM_names){
  OM_i <- get(OMname_i,envir=env.H2)
  pars_mod2[OMname_i,c("beta","cparsD")] <- c(paste(round(OM_i@beta,2),collapse=", "),paste(round(head(OM_i@cpars$D,3),3),collapse=", "))
}

```
